### ISSUE TITLE
Validator: `1 == self.nodes()... * 0` throws an exception

### ISSUE THREAD

**Issue by maxkratz** [Echtzeitsysteme/gips#60]
The validator throws an exception when comparing a static number with a multiplication that contains a node reference.

Example code:
```
constraint -> pattern::vnodeNotMapped {
	1 == self.nodes().vnode.resourceDemand * 0
}
```

Symptom:
```
java.lang.UnsupportedOperationException: Not yet implemented
	at org.emoflon.gips.gipsl.validation.GipslValidator.getNumberType(GipslValidator.java:1384)
	at org.emoflon.gips.gipsl.validation.GipslValidator.combine(GipslValidator.java:1309)
	at org.emoflon.gips.gipsl.validation.GipslValidator.getEvalTypeFromArithExpr(GipslValidator.java:847)
	at org.emoflon.gips.gipsl.validation.GipslValidator.getEvalTypeDelegate(GipslValidator.java:1221)
	at org.emoflon.gips.gipsl.validation.GipslValidator.getEvalTypeFromBoolExpr(GipslValidator.java:799)
	at org.emoflon.gips.gipsl.validation.GipslConstraintValidator.checkConstraint(GipslConstraintValidator.java:85)
	at org.emoflon.gips.gipsl.validation.GipslValidator.checkConstraint(GipslValidator.java:388)
```

**Comment by maxkratz** [comment]
May this gets only triggered if there is on `=` missing, e.g.:
```
constraint -> pattern::vnodeNotMapped {
	1 = self.nodes().vnode.resourceDemand * 0
}
```

TODO: Investigate this.
